language: node_js
node_js:
  - '0.10'
env:
  global:
    - TIKA_VERSION="1.4"
    - TIKA_DIR=`pwd`/tika-1.4
    - TIKA_PATH="$TIKA_DIR/tika-app-$TIKA_VERSION.jar"
before_install:
  - mkdir $TIKA_DIR
  - run-parts .profile.d --regex '.+'
install:
  - npm install
script:
  - npm test
deploy:
  provider: heroku
  app: anyfetch-hydrater-tika
  api_key:
    secure: co9z7le8amx0W3uXdxyneh6uZbw6dHY15WuDSWqaVoxovdvb1BYz+3UOGHVTru5jKKOmVpuqogStuWRm3JF9SqXbtuDJOZ3qhwX+Y7y/169mWboxu8zGWGF90P7xT+pwfVCiO5yKXxbREI/PrSpCe0DNNSJvlzRRqAApSPSP3dE=
  on:
    repo: Papiel/hydrater-tika
